### ISSUE TITLE
Taskkill IE driver?

### ISSUE THREAD

**Issue by xyngfei** [moneesh2011/eol-ft-runner#1]
Since it does not support IE, why there is a need to taskkill the IE process? 

![image](https://user-images.githubusercontent.com/17619539/84459921-2c380a80-ac9b-11ea-8842-863b49fae19d.png)

**Comment by moneesh2011** [comment]
Good point. IE11-related functions were part of the initial spike, and were kept for future use. We will clean up this part of the code now, however I'd like to point out that IE11 could be supported in the future if there's demand. Thanks.

**Comment by moneesh2011** [comment]
Closing this issue as done.
